services:
  game-starter:
    image: docker.io/<your-dockerhub-username>/virtuals-game-starter
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEYNAR_API_KEY=${NEYNAR_API_KEY}
      - FARCASTER_SIGNER_UUID=${FARCASTER_SIGNER_UUID}
    volumes:
      - virtuals:/app
    restart: always

volumes:
  virtuals:
